language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - jruby-head
matrix:
  include:
    # System Ruby is 2.3.7 on OSX 10.14
    - rvm: 2.3.7
      os: osx
    - rvm: 2.6
      os: osx
    - rvm: 2.7
      os: osx
# Update RubyGems and Bundler due to error with Bundler 1.16.1 and RubyGems 2.7.3
# See https://github.com/travis-ci/travis-ci/issues/8978
before_install:
- ruby ./travis-bundler.rb
- bundle install
before_script: yard gems
script: rspec
