language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5.1
  - 2.5.3
  - 2.6.0
  - 2.6.1
  - jruby-9.1.16.0
  - jruby-9.2
matrix:
  include:
    - rvm: 2.4
      os: osx
# Update RubyGems and Bundler due to error with Bundler 1.16.1 and RubyGems 2.7.3
# See https://github.com/travis-ci/travis-ci/issues/8978
before_install:
- gem install bundler -v '~> 2.0'
- bundle update --bundler
- bundle install
before_script: yard gems
script: rspec
