language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - jruby-9.0.5.0
  - jruby-9.1.16.0
matrix:
  include:
    - rvm: 2.4
      os: osx
# Update RubyGems due to error with Bundler 1.16.1 and RubyGems 2.7.3
# See https://github.com/travis-ci/travis-ci/issues/8978
before_install: gem update --system
before_script: bundle exec yard gems
script: bundle exec rspec
cache:
  - bundler
